# Generated by Django 3.0.4 on 2020-04-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('house_number', models.IntegerField()),
                ('apartment_number', models.IntegerField()),
                ('order_list', models.CharField(max_length=200)),
                ('comment', models.TextField()),
            ],
        ),
    ]
